begin;

with target_pegawai (employee_code, nama, jenis, bidang_code, is_active) as (
  values
    ('SEK-001', 'Johny Ericson Ataupah, SP., MM', 'ASN', 'SEKRETARIAT', true),
    ('SEK-002', 'Drs. Yoseph Florianus Napal, MM', 'ASN', 'SEKRETARIAT', true),
    ('SEK-003', 'Aprianus Aryantho Rondak, S.STP', 'ASN', 'SEKRETARIAT', true),
    ('SEK-004', 'Yulius B. Lico, S.Sos', 'ASN', 'SEKRETARIAT', true),
    ('SEK-005', 'Lori N. Sioh, S.Sos', 'ASN', 'SEKRETARIAT', true),
    ('SEK-006', 'Kristoforus R. Hayong, S.Kom., MM', 'ASN', 'SEKRETARIAT', true),
    ('SEK-007', 'Januarius J. B. Banase, S.Sos', 'ASN', 'SEKRETARIAT', true),
    ('SEK-008', 'Anselma Magdalena, S.Sos', 'ASN', 'SEKRETARIAT', true),
    ('SEK-009', 'Markus Radja', 'ASN', 'SEKRETARIAT', true),
    ('SEK-010', 'Sandy A. J. L. Pranadjaya, SH', 'ASN', 'SEKRETARIAT', true),
    ('SEK-011', 'Vinsensius N. T. Atidja', 'ASN', 'SEKRETARIAT', true),
    ('SEK-012', 'Alfred Marlison Mulle', 'ASN', 'SEKRETARIAT', true),
    ('SEK-013', 'Marselinus Tahu Tetik', 'ASN', 'SEKRETARIAT', true),
    ('SEK-014', 'Banni Bangngu Gada, SE', 'ASN', 'SEKRETARIAT', true),
    ('SEK-015', 'Anita Damaris Pello, SE', 'ASN', 'SEKRETARIAT', true),
    ('SEK-016', 'Sesilia Yosephina Pati, SE', 'ASN', 'SEKRETARIAT', true),
    ('SEK-017', 'Indah Jayanti, S.STP', 'ASN', 'SEKRETARIAT', true),
    ('SEK-018', 'Muhammad U. Ratu Loli', 'ASN', 'SEKRETARIAT', true),
    ('SEK-019', 'Nurmi Wahyuni, A.Md', 'ASN', 'SEKRETARIAT', true),
    ('SEK-020', 'Yefrid Nabuasa', 'ASN', 'SEKRETARIAT', true),
    ('SEK-021', 'Eugene Cornelis, SE', 'ASN', 'SEKRETARIAT', true),
    ('SEK-022', 'Dessy Nathaly Leo, SE', 'ASN', 'SEKRETARIAT', true),
    ('SEK-023', 'Muhammad I. H. Mokhsen, S.Kom', 'ASN', 'SEKRETARIAT', true),
    ('SEK-024', 'Inge Putri Dimamesa', 'ASN', 'SEKRETARIAT', true),
    ('SEK-025', 'Lusiana Virgine C. Angkur, S.Kom', 'ASN', 'SEKRETARIAT', true),
    ('SEK-026', 'Donna R. J. Donni, S.Kom', 'PPPK', 'SEKRETARIAT', true),
    ('SEK-027', 'Mariano Djogo Lainurak, S.Fil', 'PPPK', 'SEKRETARIAT', true),
    ('SEK-028', 'Harvido Aquino Rubian, SH', 'PPPK', 'SEKRETARIAT', true),
    ('SEK-029', 'Aris E. O. Laikopan, S.AB', 'PPPK', 'SEKRETARIAT', true),
    ('SEK-030', 'Lidwina Maria Ellyana, SE', 'PPPK', 'SEKRETARIAT', true),
    ('SEK-031', 'Novalia I. Putri Acry, S.IP.', 'PPPK', 'SEKRETARIAT', true),
    ('SEK-032', 'Maria Poncowati Handayani, SH', 'PPPK', 'SEKRETARIAT', true),
    ('SEK-033', 'Yuliana Lipat Purab, S.Kom', 'PPPK', 'SEKRETARIAT', true),
    ('SEK-034', 'Magdalena B. Tapobali, S.Tr.I.Kom', 'PPPK', 'SEKRETARIAT', true),
    ('SEK-035', 'Rina Juinda Laiskodat, SP', 'PPPK', 'SEKRETARIAT', true),
    ('SEK-036', 'Hasabya Eliaser Boling, S.Tr.M', 'PPPK', 'SEKRETARIAT', true),
    ('SEK-037', 'Leonardi M. N. Kulas, SE.', 'PPPK', 'SEKRETARIAT', true),
    ('SEK-038', 'Joachim A. K. Ulin, SM', 'PPPK', 'SEKRETARIAT', true),
    ('SEK-039', 'Johstin Adeliana Metkono, A.Md', 'PPPK', 'SEKRETARIAT', true),
    ('SEK-040', 'Agnes Snaver Asan, A.Md', 'PPPK', 'SEKRETARIAT', true),
    ('SEK-041', 'Merriyanti S. Koba', 'PPPK', 'SEKRETARIAT', true),
    ('SEK-042', 'Octovianus A. Kaha', 'PPPK', 'SEKRETARIAT', true),
    ('SEK-043', 'Mario M. Aloysius Laurensius', 'PPPK', 'SEKRETARIAT', true),
    ('SEK-044', 'Ramona Samiun', 'PPPK', 'SEKRETARIAT', true),
    ('SEK-045', 'Nelson Peren', 'PPPK', 'SEKRETARIAT', true),
    ('SEK-046', 'Daud Telnoni', 'PPPK', 'SEKRETARIAT', true),
    ('SEK-047', 'Jacobus Tonael', 'PPPK', 'SEKRETARIAT', true),
    ('SEK-048', 'Christianus Ronge', 'PPPK', 'SEKRETARIAT', true),
    ('SEK-049', 'Adi Arifin Johan Tefa', 'PPPK', 'SEKRETARIAT', true),
    ('SEK-050', 'Inggriani F. Kila Saduk', 'PPPK', 'SEKRETARIAT', true),
    ('SEK-051', 'Marselinus Nainoe', 'PPPK', 'SEKRETARIAT', true),
    ('PD1-001', 'Oktavianus Mare, SS', 'ASN', 'PENDAPATAN 1', true),
    ('PD1-002', 'Maria Y. D. Hendrayani, S.ST', 'ASN', 'PENDAPATAN 1', true),
    ('PD1-003', 'France F. G. Naibobe, S.STP., MM', 'ASN', 'PENDAPATAN 1', true),
    ('PD1-004', 'Yohanes Nahak, S.Kom., MT', 'ASN', 'PENDAPATAN 1', true),
    ('PD1-005', 'Maria Ivoni T. Lina, ST', 'ASN', 'PENDAPATAN 1', true),
    ('PD1-006', 'Marryquest B. Edison, SE., MM', 'ASN', 'PENDAPATAN 1', true),
    ('PD1-007', 'Luh Astiti Ariati, S.Ak', 'ASN', 'PENDAPATAN 1', true),
    ('PD1-008', 'Benny E. B. Foenay', 'ASN', 'PENDAPATAN 1', true),
    ('PD1-009', 'Arsena Marshal Adu, S.Sos', 'ASN', 'PENDAPATAN 1', true),
    ('PD1-010', 'Vinitria Cornelia Manehat, S.Kom', 'ASN', 'PENDAPATAN 1', true),
    ('PD1-011', 'Louis Adrian Lonis, S.Kom', 'ASN', 'PENDAPATAN 1', true),
    ('PD1-012', 'Felipus Yanuar K. A. Muni, S.Kom', 'ASN', 'PENDAPATAN 1', true),
    ('PD1-013', 'Jessica S. Ang Djadi, S.Kom', 'ASN', 'PENDAPATAN 1', true),
    ('PD1-014', 'Adriana Medah, SH.', 'PPPK', 'PENDAPATAN 1', true),
    ('PD1-015', 'Yuliana M. P. Jong Joko, S.Sos', 'PPPK', 'PENDAPATAN 1', true),
    ('PD1-016', 'Kenny Adrian M. Langgar, ST', 'PPPK', 'PENDAPATAN 1', true),
    ('PD1-017', 'Jovian Raymond Lico, SE', 'PPPK', 'PENDAPATAN 1', true),
    ('PD1-018', 'Maria Elisabeth Nay, ST', 'PPPK', 'PENDAPATAN 1', true),
    ('PD1-019', 'Lidya Banunaek, SE', 'PPPK', 'PENDAPATAN 1', true),
    ('PD1-020', 'Aritanto S. Hayong, SE', 'PPPK', 'PENDAPATAN 1', true),
    ('PD1-021', 'Christina M. Triyanti, SE', 'PPPK', 'PENDAPATAN 1', true),
    ('PD1-022', 'Abednego D. Imanuel Ena', 'PPPK', 'PENDAPATAN 1', true),
    ('PD1-023', 'Yuliana M. G. Mau', 'PPPK', 'PENDAPATAN 1', true),
    ('PD2-001', 'Lusia Fransiska Tiwe, ST', 'ASN', 'PENDAPATAN 2', true),
    ('PD2-002', 'Karel Eben Umbu Kaballu, S.STP', 'ASN', 'PENDAPATAN 2', true),
    ('PD2-003', 'Rolinda Inneke Foenay, S.Kom', 'ASN', 'PENDAPATAN 2', true),
    ('PD2-004', 'Kefi Z. M. Taku Bessi, SE., MM', 'ASN', 'PENDAPATAN 2', true),
    ('PD2-005', 'Antonius Fuka, S.Sos', 'ASN', 'PENDAPATAN 2', true),
    ('PD2-006', 'Fransiska Devy S. Lorang, S.IP', 'ASN', 'PENDAPATAN 2', true),
    ('PD2-007', 'Erich Alfaredo Boro, SE', 'ASN', 'PENDAPATAN 2', true),
    ('PD2-008', 'Adelbertus Lamahoda, A.Md', 'ASN', 'PENDAPATAN 2', true),
    ('PD2-009', 'Melkisedek Koa, A.Md', 'ASN', 'PENDAPATAN 2', true),
    ('PD2-010', 'Debora Kondo', 'ASN', 'PENDAPATAN 2', true),
    ('PD2-011', 'Frangky T. Mone', 'ASN', 'PENDAPATAN 2', true),
    ('PD2-012', 'Novyanti Arlyn Mau, SE', 'PPPK', 'PENDAPATAN 2', true),
    ('PD2-013', 'Celine Narumi Lomanledo, S.AB', 'PPPK', 'PENDAPATAN 2', true),
    ('PD2-014', 'Dessy I. Mone, S.Sos.', 'PPPK', 'PENDAPATAN 2', true),
    ('PD2-015', 'Yustinus Bani', 'PPPK', 'PENDAPATAN 2', true),
    ('AST1-001', 'Sany H. Tetmilay. SEAk., M.Acc', 'ASN', 'ASET 1', true),
    ('AST1-002', 'Firminus Kapitan, S.STP', 'ASN', 'ASET 1', true),
    ('AST1-003', 'Lambertus Buda, S.Sos', 'ASN', 'ASET 1', true),
    ('AST1-004', 'Jacobus Makin, ST., M.Ec.Dev.', 'ASN', 'ASET 1', true),
    ('AST1-005', 'Maryam Aras, S.Sos', 'ASN', 'ASET 1', true),
    ('AST1-006', 'Marcel F. Elim, ST', 'ASN', 'ASET 1', true),
    ('AST1-007', 'Sandra A. Suratama, SE., MM', 'ASN', 'ASET 1', true),
    ('AST1-008', 'Alfret D. I. Tunliu, S.Kom', 'ASN', 'ASET 1', true),
    ('AST1-009', 'Andreas A. Sabi, S.STP', 'ASN', 'ASET 1', true),
    ('AST1-010', 'Florinda da Costa Soares', 'ASN', 'ASET 1', true),
    ('AST1-011', 'Nadya Centini H. Koso, S.Tr.Ak', 'ASN', 'ASET 1', true),
    ('AST1-012', 'Patrisiana N. Kire Herin, S.Tr.Ak', 'ASN', 'ASET 1', true),
    ('AST1-013', 'Miryanti Kewahe Tokan, S.Pd', 'PPPK', 'ASET 1', true),
    ('AST1-014', 'Andreas H. Belang, S.Kom', 'PPPK', 'ASET 1', true),
    ('AST1-015', 'Irenius Angky Amaina, SH', 'PPPK', 'ASET 1', true),
    ('AST1-016', 'Eka Triyanti Lehilaka, SE', 'PPPK', 'ASET 1', true),
    ('AST1-017', 'Olga Adhe F. Pandie', 'PPPK', 'ASET 1', true),
    ('AST1-018', 'Marianus Ribu Kelen', 'PPPK', 'ASET 1', true),
    ('AST1-019', 'Ardimelek Lona', 'PPPK', 'ASET 1', true),
    ('AST2-001', 'Drs. Dominikus D. Payong, MA', 'ASN', 'ASET 2', true),
    ('AST2-002', 'Natalia Th. F. Saba, S.Sos., MM', 'ASN', 'ASET 2', true),
    ('AST2-003', 'Yus Ressie, SH', 'ASN', 'ASET 2', true),
    ('AST2-004', 'Maria Indah Imakulata, S.Sos', 'ASN', 'ASET 2', true),
    ('AST2-005', 'Isidorus C. Tolan Pari, SE., MM', 'ASN', 'ASET 2', true),
    ('AST2-006', 'Hilaria de Jesus Mendes, SH', 'ASN', 'ASET 2', true),
    ('AST2-007', 'Jori Bawa, SE', 'ASN', 'ASET 2', true),
    ('AST2-008', 'Ariesta Theresia Tokan, SE', 'ASN', 'ASET 2', true),
    ('AST2-009', 'Novita Adris Passu, A.Md', 'ASN', 'ASET 2', true),
    ('AST2-010', 'Semapritu Ndaomanu', 'ASN', 'ASET 2', true),
    ('AST2-011', 'Don G. E. da Costa, ST., MM', 'PPPK', 'ASET 2', true),
    ('AST2-012', 'Dominggus Wila Huky, S.AB', 'PPPK', 'ASET 2', true),
    ('AST2-013', 'Muhammad Ichsan Eke, SH', 'PPPK', 'ASET 2', true),
    ('AST2-014', 'Alfred Malaikari, SH', 'PPPK', 'ASET 2', true),
    ('AST2-015', 'Anselmus D. Sanga, S.Kom', 'PPPK', 'ASET 2', true),
    ('AST2-016', 'Fransiskus Alexander Pawe, S.IP', 'PPPK', 'ASET 2', true),
    ('AST2-017', 'Astrid Katty B. Koreh', 'PPPK', 'ASET 2', true),
    ('AST2-018', 'Yahya Libing', 'PPPK', 'ASET 2', true),
    ('AST2-019', 'Eben C. Foenay', 'PPPK', 'ASET 2', true),
    ('AST2-020', 'Vega N. Mudin', 'PPPK', 'ASET 2', true)
),
updated_rows as (
  update public.app_pegawai as pegawai
  set
    employee_code = target.employee_code,
    jenis = target.jenis,
    bidang_code = target.bidang_code,
    is_active = target.is_active,
    updated_at = now()
  from target_pegawai as target
  where pegawai.nama = target.nama
  returning pegawai.nama
)
insert into public.app_pegawai (employee_code, nama, jenis, bidang_code, is_active)
select
  target.employee_code,
  target.nama,
  target.jenis,
  target.bidang_code,
  target.is_active
from target_pegawai as target
where not exists (
  select 1
  from public.app_pegawai as pegawai
  where pegawai.nama = target.nama
);

commit;
