const STORAGE_KEYS = {
  session: "bpad-attendance-session",
  attendance: "bpad-attendance-data",
  reports: "bpad-daily-reports",
};

const STATUS_OPTIONS = [
  "hadir",
  "sakit",
  "izin",
  "cuti",
  "terlambat",
  "tugas",
  "tubel",
];

const STATUS_LABELS = {
  hadir: "Hadir",
  sakit: "Sakit",
  izin: "Izin",
  cuti: "Cuti",
  terlambat: "Terlambat",
  tugas: "Tugas",
  tubel: "Tubel",
};

const ACCOUNTS = [
  {
    username: "Badan Pendapatan dan Aset Daerah",
    scope: "ALL",
  },
  {
    username: "SEKRETARIAT",
    scope: ["SEKRETARIAT"],
  },
  {
    username: "PENDAPATAN 1",
    scope: ["PENDAPATAN 1"],
  },
  {
    username: "PENDAPATAN 2",
    scope: ["PENDAPATAN 2"],
  },
  {
    username: "ASET 1",
    scope: ["ASET 1"],
  },
  {
    username: "ASET 2",
    scope: ["ASET 2"],
  },
];

const EMPLOYEES = {
  SEKRETARIAT: [
    { id: "SEK-001", nama: "Johny Ericson Ataupah, SP., MM", bidang: "SEKRETARIAT", jenis: "ASN" },
    { id: "SEK-002", nama: "Drs. Yoseph Florianus Napal, MM", bidang: "SEKRETARIAT", jenis: "ASN" },
    { id: "SEK-003", nama: "Aprianus Aryantho Rondak, S.STP", bidang: "SEKRETARIAT", jenis: "ASN" },
    { id: "SEK-004", nama: "Yulius B. Lico, S.Sos", bidang: "SEKRETARIAT", jenis: "ASN" },
    { id: "SEK-005", nama: "Lori N. Sioh, S.Sos", bidang: "SEKRETARIAT", jenis: "ASN" },
    { id: "SEK-006", nama: "Kristoforus R. Hayong, S.Kom., MM", bidang: "SEKRETARIAT", jenis: "ASN" },
    { id: "SEK-007", nama: "Januarius J. B. Banase, S.Sos", bidang: "SEKRETARIAT", jenis: "ASN" },
    { id: "SEK-008", nama: "Anselma Magdalena, S.Sos", bidang: "SEKRETARIAT", jenis: "ASN" },
    { id: "SEK-009", nama: "Markus Radja", bidang: "SEKRETARIAT", jenis: "ASN" },
    { id: "SEK-010", nama: "Sandy A. J. L. Pranadjaya, SH", bidang: "SEKRETARIAT", jenis: "ASN" },
    { id: "SEK-011", nama: "Vinsensius N. T. Atidja", bidang: "SEKRETARIAT", jenis: "ASN" },
    { id: "SEK-012", nama: "Alfred Marlison Mulle", bidang: "SEKRETARIAT", jenis: "ASN" },
    { id: "SEK-013", nama: "Marselinus Tahu Tetik", bidang: "SEKRETARIAT", jenis: "ASN" },
    { id: "SEK-014", nama: "Banni Bangngu Gada, SE", bidang: "SEKRETARIAT", jenis: "ASN" },
    { id: "SEK-015", nama: "Anita Damaris Pello, SE", bidang: "SEKRETARIAT", jenis: "ASN" },
    { id: "SEK-016", nama: "Sesilia Yosephina Pati, SE", bidang: "SEKRETARIAT", jenis: "ASN" },
    { id: "SEK-017", nama: "Indah Jayanti, S.STP", bidang: "SEKRETARIAT", jenis: "ASN" },
    { id: "SEK-018", nama: "Muhammad U. Ratu Loli", bidang: "SEKRETARIAT", jenis: "ASN" },
    { id: "SEK-019", nama: "Nurmi Wahyuni, A.Md", bidang: "SEKRETARIAT", jenis: "ASN" },
    { id: "SEK-020", nama: "Yefrid Nabuasa", bidang: "SEKRETARIAT", jenis: "ASN" },
    { id: "SEK-021", nama: "Eugene Cornelis, SE", bidang: "SEKRETARIAT", jenis: "ASN" },
    { id: "SEK-022", nama: "Dessy Nathaly Leo, SE", bidang: "SEKRETARIAT", jenis: "ASN" },
    { id: "SEK-023", nama: "Muhammad I. H. Mokhsen, S.Kom", bidang: "SEKRETARIAT", jenis: "ASN" },
    { id: "SEK-024", nama: "Inge Putri Dimamesa", bidang: "SEKRETARIAT", jenis: "ASN" },
    { id: "SEK-025", nama: "Lusiana Virgine C. Angkur, S.Kom", bidang: "SEKRETARIAT", jenis: "ASN" },
    { id: "SEK-026", nama: "Donna R. J. Donni, S.Kom", bidang: "SEKRETARIAT", jenis: "PPPK" },
    { id: "SEK-027", nama: "Mariano Djogo Lainurak, S.Fil", bidang: "SEKRETARIAT", jenis: "PPPK" },
    { id: "SEK-028", nama: "Harvido Aquino Rubian, SH", bidang: "SEKRETARIAT", jenis: "PPPK" },
    { id: "SEK-029", nama: "Aris E. O. Laikopan, S.AB", bidang: "SEKRETARIAT", jenis: "PPPK" },
    { id: "SEK-030", nama: "Lidwina Maria Ellyana, SE", bidang: "SEKRETARIAT", jenis: "PPPK" },
    { id: "SEK-031", nama: "Novalia I. Putri Acry, S.IP.", bidang: "SEKRETARIAT", jenis: "PPPK" },
    { id: "SEK-032", nama: "Maria Poncowati Handayani, SH", bidang: "SEKRETARIAT", jenis: "PPPK" },
    { id: "SEK-033", nama: "Yuliana Lipat Purab, S.Kom", bidang: "SEKRETARIAT", jenis: "PPPK" },
    { id: "SEK-034", nama: "Magdalena B. Tapobali, S.Tr.I.Kom", bidang: "SEKRETARIAT", jenis: "PPPK" },
    { id: "SEK-035", nama: "Rina Juinda Laiskodat, SP", bidang: "SEKRETARIAT", jenis: "PPPK" },
    { id: "SEK-036", nama: "Hasabya Eliaser Boling, S.Tr.M", bidang: "SEKRETARIAT", jenis: "PPPK" },
    { id: "SEK-037", nama: "Leonardi M. N. Kulas, SE.", bidang: "SEKRETARIAT", jenis: "PPPK" },
    { id: "SEK-038", nama: "Joachim A. K. Ulin, SM", bidang: "SEKRETARIAT", jenis: "PPPK" },
    { id: "SEK-039", nama: "Johstin Adeliana Metkono, A.Md", bidang: "SEKRETARIAT", jenis: "PPPK" },
    { id: "SEK-040", nama: "Agnes Snaver Asan, A.Md", bidang: "SEKRETARIAT", jenis: "PPPK" },
    { id: "SEK-041", nama: "Merriyanti S. Koba", bidang: "SEKRETARIAT", jenis: "PPPK" },
    { id: "SEK-042", nama: "Octovianus A. Kaha", bidang: "SEKRETARIAT", jenis: "PPPK" },
    { id: "SEK-043", nama: "Mario M. Aloysius Laurensius", bidang: "SEKRETARIAT", jenis: "PPPK" },
    { id: "SEK-044", nama: "Ramona Samiun", bidang: "SEKRETARIAT", jenis: "PPPK" },
    { id: "SEK-045", nama: "Nelson Peren", bidang: "SEKRETARIAT", jenis: "PPPK" },
    { id: "SEK-046", nama: "Daud Telnoni", bidang: "SEKRETARIAT", jenis: "PPPK" },
    { id: "SEK-047", nama: "Jacobus Tonael", bidang: "SEKRETARIAT", jenis: "PPPK" },
    { id: "SEK-048", nama: "Christianus Ronge", bidang: "SEKRETARIAT", jenis: "PPPK" },
    { id: "SEK-049", nama: "Adi Arifin Johan Tefa", bidang: "SEKRETARIAT", jenis: "PPPK" },
    { id: "SEK-050", nama: "Inggriani F. Kila Saduk", bidang: "SEKRETARIAT", jenis: "PPPK" },
    { id: "SEK-051", nama: "Marselinus Nainoe", bidang: "SEKRETARIAT", jenis: "PPPK" },
  ],
  "PENDAPATAN 1": [
    { id: "PD1-001", nama: "Oktavianus Mare, SS", bidang: "PENDAPATAN 1", jenis: "ASN" },
    { id: "PD1-002", nama: "Maria Y. D. Hendrayani, S.ST", bidang: "PENDAPATAN 1", jenis: "ASN" },
    { id: "PD1-003", nama: "France F. G. Naibobe, S.STP., MM", bidang: "PENDAPATAN 1", jenis: "ASN" },
    { id: "PD1-004", nama: "Yohanes Nahak, S.Kom., MT", bidang: "PENDAPATAN 1", jenis: "ASN" },
    { id: "PD1-005", nama: "Maria Ivoni T. Lina, ST", bidang: "PENDAPATAN 1", jenis: "ASN" },
    { id: "PD1-006", nama: "Marryquest B. Edison, SE., MM", bidang: "PENDAPATAN 1", jenis: "ASN" },
    { id: "PD1-007", nama: "Luh Astiti Ariati, S.Ak", bidang: "PENDAPATAN 1", jenis: "ASN" },
    { id: "PD1-008", nama: "Benny E. B. Foenay", bidang: "PENDAPATAN 1", jenis: "ASN" },
    { id: "PD1-009", nama: "Arsena Marshal Adu, S.Sos", bidang: "PENDAPATAN 1", jenis: "ASN" },
    { id: "PD1-010", nama: "Vinitria Cornelia Manehat, S.Kom", bidang: "PENDAPATAN 1", jenis: "ASN" },
    { id: "PD1-011", nama: "Louis Adrian Lonis, S.Kom", bidang: "PENDAPATAN 1", jenis: "ASN" },
    { id: "PD1-012", nama: "Felipus Yanuar K. A. Muni, S.Kom", bidang: "PENDAPATAN 1", jenis: "ASN" },
    { id: "PD1-013", nama: "Jessica S. Ang Djadi, S.Kom", bidang: "PENDAPATAN 1", jenis: "ASN" },
    { id: "PD1-014", nama: "Adriana Medah, SH.", bidang: "PENDAPATAN 1", jenis: "PPPK" },
    { id: "PD1-015", nama: "Yuliana M. P. Jong Joko, S.Sos", bidang: "PENDAPATAN 1", jenis: "PPPK" },
    { id: "PD1-016", nama: "Kenny Adrian M. Langgar, ST", bidang: "PENDAPATAN 1", jenis: "PPPK" },
    { id: "PD1-017", nama: "Jovian Raymond Lico, SE", bidang: "PENDAPATAN 1", jenis: "PPPK" },
    { id: "PD1-018", nama: "Maria Elisabeth Nay, ST", bidang: "PENDAPATAN 1", jenis: "PPPK" },
    { id: "PD1-019", nama: "Lidya Banunaek, SE", bidang: "PENDAPATAN 1", jenis: "PPPK" },
    { id: "PD1-020", nama: "Aritanto S. Hayong, SE", bidang: "PENDAPATAN 1", jenis: "PPPK" },
    { id: "PD1-021", nama: "Christina M. Triyanti, SE", bidang: "PENDAPATAN 1", jenis: "PPPK" },
    { id: "PD1-022", nama: "Abednego D. Imanuel Ena", bidang: "PENDAPATAN 1", jenis: "PPPK" },
    { id: "PD1-023", nama: "Yuliana M. G. Mau", bidang: "PENDAPATAN 1", jenis: "PPPK" },
  ],
  "PENDAPATAN 2": [
    { id: "PD2-001", nama: "Lusia Fransiska Tiwe, ST", bidang: "PENDAPATAN 2", jenis: "ASN" },
    { id: "PD2-002", nama: "Karel Eben Umbu Kaballu, S.STP", bidang: "PENDAPATAN 2", jenis: "ASN" },
    { id: "PD2-003", nama: "Rolinda Inneke Foenay, S.Kom", bidang: "PENDAPATAN 2", jenis: "ASN" },
    { id: "PD2-004", nama: "Kefi Z. M. Taku Bessi, SE., MM", bidang: "PENDAPATAN 2", jenis: "ASN" },
    { id: "PD2-005", nama: "Antonius Fuka, S.Sos", bidang: "PENDAPATAN 2", jenis: "ASN" },
    { id: "PD2-006", nama: "Fransiska Devy S. Lorang, S.IP", bidang: "PENDAPATAN 2", jenis: "ASN" },
    { id: "PD2-007", nama: "Erich Alfaredo Boro, SE", bidang: "PENDAPATAN 2", jenis: "ASN" },
    { id: "PD2-008", nama: "Adelbertus Lamahoda, A.Md", bidang: "PENDAPATAN 2", jenis: "ASN" },
    { id: "PD2-009", nama: "Melkisedek Koa, A.Md", bidang: "PENDAPATAN 2", jenis: "ASN" },
    { id: "PD2-010", nama: "Debora Kondo", bidang: "PENDAPATAN 2", jenis: "ASN" },
    { id: "PD2-011", nama: "Frangky T. Mone", bidang: "PENDAPATAN 2", jenis: "ASN" },
    { id: "PD2-012", nama: "Novyanti Arlyn Mau, SE", bidang: "PENDAPATAN 2", jenis: "PPPK" },
    { id: "PD2-013", nama: "Celine Narumi Lomanledo, S.AB", bidang: "PENDAPATAN 2", jenis: "PPPK" },
    { id: "PD2-014", nama: "Dessy I. Mone, S.Sos.", bidang: "PENDAPATAN 2", jenis: "PPPK" },
    { id: "PD2-015", nama: "Yustinus Bani", bidang: "PENDAPATAN 2", jenis: "PPPK" },
  ],
  "ASET 1": [
    { id: "AST1-001", nama: "Sany H. Tetmilay. SEAk., M.Acc", bidang: "ASET 1", jenis: "ASN" },
    { id: "AST1-002", nama: "Firminus Kapitan, S.STP", bidang: "ASET 1", jenis: "ASN" },
    { id: "AST1-003", nama: "Lambertus Buda, S.Sos", bidang: "ASET 1", jenis: "ASN" },
    { id: "AST1-004", nama: "Jacobus Makin, ST., M.Ec.Dev.", bidang: "ASET 1", jenis: "ASN" },
    { id: "AST1-005", nama: "Maryam Aras, S.Sos", bidang: "ASET 1", jenis: "ASN" },
    { id: "AST1-006", nama: "Marcel F. Elim, ST", bidang: "ASET 1", jenis: "ASN" },
    { id: "AST1-007", nama: "Sandra A. Suratama, SE., MM", bidang: "ASET 1", jenis: "ASN" },
    { id: "AST1-008", nama: "Alfret D. I. Tunliu, S.Kom", bidang: "ASET 1", jenis: "ASN" },
    { id: "AST1-009", nama: "Andreas A. Sabi, S.STP", bidang: "ASET 1", jenis: "ASN" },
    { id: "AST1-010", nama: "Florinda da Costa Soares", bidang: "ASET 1", jenis: "ASN" },
    { id: "AST1-011", nama: "Nadya Centini H. Koso, S.Tr.Ak", bidang: "ASET 1", jenis: "ASN" },
    { id: "AST1-012", nama: "Patrisiana N. Kire Herin, S.Tr.Ak", bidang: "ASET 1", jenis: "ASN" },
    { id: "AST1-013", nama: "Miryanti Kewahe Tokan, S.Pd", bidang: "ASET 1", jenis: "PPPK" },
    { id: "AST1-014", nama: "Andreas H. Belang, S.Kom", bidang: "ASET 1", jenis: "PPPK" },
    { id: "AST1-015", nama: "Irenius Angky Amaina, SH", bidang: "ASET 1", jenis: "PPPK" },
    { id: "AST1-016", nama: "Eka Triyanti Lehilaka, SE", bidang: "ASET 1", jenis: "PPPK" },
    { id: "AST1-017", nama: "Olga Adhe F. Pandie", bidang: "ASET 1", jenis: "PPPK" },
    { id: "AST1-018", nama: "Marianus Ribu Kelen", bidang: "ASET 1", jenis: "PPPK" },
    { id: "AST1-019", nama: "Ardimelek Lona", bidang: "ASET 1", jenis: "PPPK" },
  ],
  "ASET 2": [
    { id: "AST2-001", nama: "Drs. Dominikus D. Payong, MA", bidang: "ASET 2", jenis: "ASN" },
    { id: "AST2-002", nama: "Natalia Th. F. Saba, S.Sos., MM", bidang: "ASET 2", jenis: "ASN" },
    { id: "AST2-003", nama: "Yus Ressie, SH", bidang: "ASET 2", jenis: "ASN" },
    { id: "AST2-004", nama: "Maria Indah Imakulata, S.Sos", bidang: "ASET 2", jenis: "ASN" },
    { id: "AST2-005", nama: "Isidorus C. Tolan Pari, SE., MM", bidang: "ASET 2", jenis: "ASN" },
    { id: "AST2-006", nama: "Hilaria de Jesus Mendes, SH", bidang: "ASET 2", jenis: "ASN" },
    { id: "AST2-007", nama: "Jori Bawa, SE", bidang: "ASET 2", jenis: "ASN" },
    { id: "AST2-008", nama: "Ariesta Theresia Tokan, SE", bidang: "ASET 2", jenis: "ASN" },
    { id: "AST2-009", nama: "Novita Adris Passu, A.Md", bidang: "ASET 2", jenis: "ASN" },
    { id: "AST2-010", nama: "Semapritu Ndaomanu", bidang: "ASET 2", jenis: "ASN" },
    { id: "AST2-011", nama: "Don G. E. da Costa, ST., MM", bidang: "ASET 2", jenis: "PPPK" },
    { id: "AST2-012", nama: "Dominggus Wila Huky, S.AB", bidang: "ASET 2", jenis: "PPPK" },
    { id: "AST2-013", nama: "Muhammad Ichsan Eke, SH", bidang: "ASET 2", jenis: "PPPK" },
    { id: "AST2-014", nama: "Alfred Malaikari, SH", bidang: "ASET 2", jenis: "PPPK" },
    { id: "AST2-015", nama: "Anselmus D. Sanga, S.Kom", bidang: "ASET 2", jenis: "PPPK" },
    { id: "AST2-016", nama: "Fransiskus Alexander Pawe, S.IP", bidang: "ASET 2", jenis: "PPPK" },
    { id: "AST2-017", nama: "Astrid Katty B. Koreh", bidang: "ASET 2", jenis: "PPPK" },
    { id: "AST2-018", nama: "Yahya Libing", bidang: "ASET 2", jenis: "PPPK" },
    { id: "AST2-019", nama: "Eben C. Foenay", bidang: "ASET 2", jenis: "PPPK" },
    { id: "AST2-020", nama: "Vega N. Mudin", bidang: "ASET 2", jenis: "PPPK" },
  ],
};

const state = {
  currentUser: null,
  activeDate: getTodayKey(),
  currentReport: null,
  selectedMonitoringBidang: null,
  employeeDirectory: EMPLOYEES,
};

const elements = {
  loginView: document.getElementById("loginView"),
  dashboardView: document.getElementById("dashboardView"),
  loginForm: document.getElementById("loginForm"),
  accountSelect: document.getElementById("accountSelect"),
  passwordInput: document.getElementById("passwordInput"),
  loginSubmitBtn: document.getElementById("loginSubmitBtn"),
  loginOverlay: document.getElementById("loginOverlay"),
  loginOverlaySpinner: document.getElementById("loginOverlaySpinner"),
  loginMessage: document.getElementById("loginMessage"),
  todayLabel: document.getElementById("todayLabel"),
  liveClock: document.getElementById("liveClock"),
  toastContainer: document.getElementById("toastContainer"),
  activeAccountName: document.getElementById("activeAccountName"),
  activeDateInput: document.getElementById("activeDateInput"),
  scopeInput: document.getElementById("scopeInput"),
  summaryTitle: document.getElementById("summaryTitle"),
  freezeNotice: document.getElementById("freezeNotice"),
  summaryCards: document.getElementById("summaryCards"),
  monitoringPanel: document.getElementById("monitoringPanel"),
  monitoringCards: document.getElementById("monitoringCards"),
  reportedSummary: document.getElementById("reportedSummary"),
  attendancePanel: document.getElementById("attendancePanel"),
  attendanceTitle: document.getElementById("attendanceTitle"),
  attendanceHint: document.getElementById("attendanceHint"),
  attendanceContainer: document.getElementById("attendanceContainer"),
  startAttendanceBtn: document.getElementById("startAttendanceBtn"),
  logoutBtn: document.getElementById("logoutBtn"),
  generateReportBtn: document.getElementById("generateReportBtn"),
  openMonthlyBtn: document.getElementById("openMonthlyBtn"),
  reportModal: document.getElementById("reportModal"),
  reportContent: document.getElementById("reportContent"),
  exportReportExcelBtn: document.getElementById("exportReportExcelBtn"),
  exportReportPdfBtn: document.getElementById("exportReportPdfBtn"),
  saveReportBtn: document.getElementById("saveReportBtn"),
  monthlyModal: document.getElementById("monthlyModal"),
  monthPicker: document.getElementById("monthPicker"),
  refreshMonthlyBtn: document.getElementById("refreshMonthlyBtn"),
  monthlyContent: document.getElementById("monthlyContent"),
  exportMonthlyExcelBtn: document.getElementById("exportMonthlyExcelBtn"),
  exportMonthlyPdfBtn: document.getElementById("exportMonthlyPdfBtn"),
};
